// ... existing code ...

const product = new Product({
  // ... other fields ...
  category: {
    main: req.body.category.main,    // Make sure this is provided
    sub: req.body.category.sub       // Make sure this is provided
  },
  // ... other fields ...
});

// ... existing code ...